### ISSUE TITLE
In NetworkX >= 2.0 graphs have no attribute 'node'

### ISSUE THREAD

**Issue by patrikTSS** [globality-corp/sklearn-hierarchical-classification#28]
In NetworkX >= 2.0 graphs have no attribute 'node'.

See https://networkx.github.io/documentation/stable/release/migration_guide_from_1.x_to_2.0.html
> The Graph attributes G.node and G.edge have been removed in favor of using G.nodes[n] and G.edges[u, v]. 

The node attribute node is used in HierarchicalClassifier multiple times, e.g. in line 262:
`if "X" in self.graph_.node[node_id]:`

If I try to fit a model I get the error:

> AttributeError: 'DiGraph' object has no attribute 'node'

**Comment by patrikTSS** [comment]
I can changed graph.node to graph.node on several places and then it works with networkX 2.0.
I can create a PR if you want.

**Comment by adamhadani** [comment]
fixed by #30 - I also just made release `1.2.0` to PyPI which includes this. thanks for reporting and happy new year!
